#!/bin/bash

function send_notification() {
	volume=$(pamixer --get-volume)
	notify-send -a "changevolume" -u low -h string:x-canonical-private-synchronous:volume -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	pamixer -u
	pamixer -i 5 --allow-boost
	send_notification $1
	;;
down)
	pamixer -u
	pamixer -d 5 --allow-boost
	send_notification $1
	;;
mute)
	pamixer -t
	if $(pamixer --get-mute); then
		notify-send -i volume-mute -a "changevolume" -h string:x-canonical-private-synchronous:volume -t 2000 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac
